# Change these first
owner: itsolver # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: IT Solver
    url: https://www.itsolver.net
  - name: IT Solver Support
    url: https://support.itsolver.net
  - name: IT Solver Shop
    url: https://shop.itsolver.net

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.itsolver.net
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/itsolver/upptime/master/it-solver-logo.svg
  name: System Status
  introTitle: "Need help with something?"
  introMessage: Visit [itsolver.net/contact](https://www.itsolver.net/contact) to get in touch.
  navbar:
    - title: Status
      href: /
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
assignees:
  - itsolver
